// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.23.1
// source: person/person.proto

package person

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	home "qimiaoPB/pb/home"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Person_Sex int32

const (
	Person_male   Person_Sex = 0
	Person_female Person_Sex = 1
	Person_women  Person_Sex = 1
	Person_girl   Person_Sex = 1
	Person_others Person_Sex = 2
)

// Enum value maps for Person_Sex.
var (
	Person_Sex_name = map[int32]string{
		0: "male",
		1: "female",
		// Duplicate value: 1: "women",
		// Duplicate value: 1: "girl",
		2: "others",
	}
	Person_Sex_value = map[string]int32{
		"male":   0,
		"female": 1,
		"women":  1,
		"girl":   1,
		"others": 2,
	}
)

func (x Person_Sex) Enum() *Person_Sex {
	p := new(Person_Sex)
	*p = x
	return p
}

func (x Person_Sex) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Person_Sex) Descriptor() protoreflect.EnumDescriptor {
	return file_person_person_proto_enumTypes[0].Descriptor()
}

func (Person_Sex) Type() protoreflect.EnumType {
	return &file_person_person_proto_enumTypes[0]
}

func (x Person_Sex) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Person_Sex.Descriptor instead.
func (Person_Sex) EnumDescriptor() ([]byte, []int) {
	return file_person_person_proto_rawDescGZIP(), []int{0, 0}
}

//	message Home{
//	    repeated Person persons = 1;
//	    message Vistor{
//	        string name = 1;
//	    }
//	    Vistor v = 2;
//	}
type Person struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age    int32      `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	Dead   bool       `protobuf:"varint,3,opt,name=dead,proto3" json:"dead,omitempty"`
	Gender Person_Sex `protobuf:"varint,4,opt,name=gender,proto3,enum=person.Person_Sex" json:"gender,omitempty"`
	PHome  *home.Home `protobuf:"bytes,6,opt,name=p_home,json=pHome,proto3" json:"p_home,omitempty"`
	// Types that are assignable to HighestEducation:
	//
	//	*Person_PrimarySchool
	//	*Person_MiddleSchool
	//	*Person_University
	HighestEducation isPerson_HighestEducation `protobuf_oneof:"highestEducation"`
}

func (x *Person) Reset() {
	*x = Person{}
	if protoimpl.UnsafeEnabled {
		mi := &file_person_person_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Person) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Person) ProtoMessage() {}

func (x *Person) ProtoReflect() protoreflect.Message {
	mi := &file_person_person_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Person.ProtoReflect.Descriptor instead.
func (*Person) Descriptor() ([]byte, []int) {
	return file_person_person_proto_rawDescGZIP(), []int{0}
}

func (x *Person) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Person) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *Person) GetDead() bool {
	if x != nil {
		return x.Dead
	}
	return false
}

func (x *Person) GetGender() Person_Sex {
	if x != nil {
		return x.Gender
	}
	return Person_male
}

func (x *Person) GetPHome() *home.Home {
	if x != nil {
		return x.PHome
	}
	return nil
}

func (m *Person) GetHighestEducation() isPerson_HighestEducation {
	if m != nil {
		return m.HighestEducation
	}
	return nil
}

func (x *Person) GetPrimarySchool() string {
	if x, ok := x.GetHighestEducation().(*Person_PrimarySchool); ok {
		return x.PrimarySchool
	}
	return ""
}

func (x *Person) GetMiddleSchool() string {
	if x, ok := x.GetHighestEducation().(*Person_MiddleSchool); ok {
		return x.MiddleSchool
	}
	return ""
}

func (x *Person) GetUniversity() string {
	if x, ok := x.GetHighestEducation().(*Person_University); ok {
		return x.University
	}
	return ""
}

type isPerson_HighestEducation interface {
	isPerson_HighestEducation()
}

type Person_PrimarySchool struct {
	PrimarySchool string `protobuf:"bytes,7,opt,name=primarySchool,proto3,oneof"`
}

type Person_MiddleSchool struct {
	MiddleSchool string `protobuf:"bytes,8,opt,name=middleSchool,proto3,oneof"`
}

type Person_University struct {
	University string `protobuf:"bytes,9,opt,name=University,proto3,oneof"`
}

func (*Person_PrimarySchool) isPerson_HighestEducation() {}

func (*Person_MiddleSchool) isPerson_HighestEducation() {}

func (*Person_University) isPerson_HighestEducation() {}

var File_person_person_proto protoreflect.FileDescriptor

var file_person_person_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x2f, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x1a, 0x0f, 0x68,
	0x6f, 0x6d, 0x65, 0x2f, 0x68, 0x6f, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe7,
	0x02, 0x0a, 0x06, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x61, 0x67, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x64, 0x65, 0x61, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x64,
	0x65, 0x61, 0x64, 0x12, 0x2a, 0x0a, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x2e, 0x50, 0x65, 0x72,
	0x73, 0x6f, 0x6e, 0x2e, 0x53, 0x65, 0x78, 0x52, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12,
	0x21, 0x0a, 0x06, 0x70, 0x5f, 0x68, 0x6f, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0a, 0x2e, 0x68, 0x6f, 0x6d, 0x65, 0x2e, 0x48, 0x6f, 0x6d, 0x65, 0x52, 0x05, 0x70, 0x48, 0x6f,
	0x6d, 0x65, 0x12, 0x26, 0x0a, 0x0d, 0x70, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x53, 0x63, 0x68,
	0x6f, 0x6f, 0x6c, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0d, 0x70, 0x72, 0x69,
	0x6d, 0x61, 0x72, 0x79, 0x53, 0x63, 0x68, 0x6f, 0x6f, 0x6c, 0x12, 0x24, 0x0a, 0x0c, 0x6d, 0x69,
	0x64, 0x64, 0x6c, 0x65, 0x53, 0x63, 0x68, 0x6f, 0x6f, 0x6c, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x00, 0x52, 0x0c, 0x6d, 0x69, 0x64, 0x64, 0x6c, 0x65, 0x53, 0x63, 0x68, 0x6f, 0x6f, 0x6c,
	0x12, 0x20, 0x0a, 0x0a, 0x55, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x69, 0x74, 0x79, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0a, 0x55, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x74, 0x79, 0x22, 0x40, 0x0a, 0x03, 0x53, 0x65, 0x78, 0x12, 0x08, 0x0a, 0x04, 0x6d, 0x61, 0x6c,
	0x65, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x66, 0x65, 0x6d, 0x61, 0x6c, 0x65, 0x10, 0x01, 0x12,
	0x09, 0x0a, 0x05, 0x77, 0x6f, 0x6d, 0x65, 0x6e, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x67, 0x69,
	0x72, 0x6c, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x73, 0x10, 0x02,
	0x1a, 0x02, 0x10, 0x01, 0x42, 0x12, 0x0a, 0x10, 0x68, 0x69, 0x67, 0x68, 0x65, 0x73, 0x74, 0x45,
	0x64, 0x75, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4a, 0x04, 0x08, 0x05, 0x10, 0x06, 0x52, 0x05,
	0x73, 0x6c, 0x69, 0x63, 0x65, 0x52, 0x01, 0x6d, 0x42, 0x1b, 0x5a, 0x19, 0x71, 0x69, 0x6d, 0x69,
	0x61, 0x6f, 0x50, 0x42, 0x2f, 0x70, 0x62, 0x2f, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x3b, 0x70,
	0x65, 0x72, 0x73, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_person_person_proto_rawDescOnce sync.Once
	file_person_person_proto_rawDescData = file_person_person_proto_rawDesc
)

func file_person_person_proto_rawDescGZIP() []byte {
	file_person_person_proto_rawDescOnce.Do(func() {
		file_person_person_proto_rawDescData = protoimpl.X.CompressGZIP(file_person_person_proto_rawDescData)
	})
	return file_person_person_proto_rawDescData
}

var file_person_person_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_person_person_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_person_person_proto_goTypes = []interface{}{
	(Person_Sex)(0),   // 0: person.Person.Sex
	(*Person)(nil),    // 1: person.Person
	(*home.Home)(nil), // 2: home.Home
}
var file_person_person_proto_depIdxs = []int32{
	0, // 0: person.Person.gender:type_name -> person.Person.Sex
	2, // 1: person.Person.p_home:type_name -> home.Home
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_person_person_proto_init() }
func file_person_person_proto_init() {
	if File_person_person_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_person_person_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Person); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_person_person_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Person_PrimarySchool)(nil),
		(*Person_MiddleSchool)(nil),
		(*Person_University)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_person_person_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_person_person_proto_goTypes,
		DependencyIndexes: file_person_person_proto_depIdxs,
		EnumInfos:         file_person_person_proto_enumTypes,
		MessageInfos:      file_person_person_proto_msgTypes,
	}.Build()
	File_person_person_proto = out.File
	file_person_person_proto_rawDesc = nil
	file_person_person_proto_goTypes = nil
	file_person_person_proto_depIdxs = nil
}
